name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Déploie à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true  # Pour récupérer le thème PaperMod
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
#        cname: portfolio.mondomaine.com  # Supprimer ou changer si pas de domaine perso
